---
# Items that apply to ALL profiles: 
# If 3 replicas of Eureka is needed: defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  
---
spring:
  profiles: SearchDev
assets: LF_Avengers,Axeda_007,LF_Thor,Axeda_Thanga_001,LF_Strange,LF_Superman
  
---
spring:
  profiles: SearchStg
assets: RVF_Avengers,Axeda_500,RVF_Binay,Axeda_RSvP_100,RVF_Nature,RVF_Hitman

---
spring:
  profiles: SearchProd
assets: PF_Prod_Avengers,Axeda_Prod_907,PF_Prod_Thor,Axeda_Prod_708,PF_Prod,PF_Super_Prod

---
spring:
  profiles: FileTransferDev
files: hcds.xml,provisioning.xml,OpenSSLConfig.xml,PolicyActionGroups.xml,SystemResource.xml,xGate.log
  
---
spring:
  profiles: FileTransferStg
files: hcds.xml,provisioning.xml,OpenSSLConfig.xml,PolicyActionGroups.xml,SystemResource.xml,xGate.log

---
spring:
  profiles: FileTransferProd
files: hcds.xml,provisioning.xml,OpenSSLConfig.xml,PolicyActionGroups.xml,SystemResource.xml,xGate.log

---
spring:
  profiles: SoftwarePackageMgmtServiceDev
packages: Sw_Pkg-809767_Dev,Sw_Pkg-876543_Dev,Sw_Pkg-973589_Dev,Sw_Pkg-453565_Dev,Sw_Pkg-65376_Dev
  
---
spring:
  profiles: SoftwarePackageMgmtServiceStg
packages: Sw_Pkg-532267_Stg,Sw_Pkg-176345_Stg,Sw_Pkg-653229_Stg,Sw_Pkg-324344_Stg,Sw_Pkg-209807_Stg

---
spring:
  profiles: SoftwarePackageMgmtServiceProd
packages: Sw_Pkg-287462_Prod,Sw_Pkg-75445_Prod,Sw_Pkg-876342_Prod,Sw_Pkg-12334_Prod,Sw_Pkg-64538_Prod
